CREATE TABLE IF NOT EXISTS OAUTH_CLIENT_DETAILS (
  CLIENT_ID VARCHAR(200) PRIMARY KEY,
  RESOURCE_IDS VARCHAR(200),
  CLIENT_SECRET VARCHAR(200) NOT NULL,
  SCOPE VARCHAR(200),
  AUTHORIZED_GRANT_TYPES VARCHAR(200),
  WEB_SERVER_REDIRECT_URI VARCHAR(200),
  AUTHORITIES VARCHAR(200),
  ACCESS_TOKEN_VALIDITY INTEGER,
  REFRESH_TOKEN_VALIDITY INTEGER,
  ADDITIONAL_INFORMATION VARCHAR(400),
  AUTOAPPROVE VARCHAR(200)
);

CREATE TABLE IF NOT EXISTS OAUTH_CLIENT_TOKEN (
  TOKEN_ID VARCHAR(200),
  TOKEN BLOB,
  AUTHENTICATION_ID VARCHAR(200) PRIMARY KEY,
  USER_NAME VARCHAR(200),
  CLIENT_ID VARCHAR(200)
);

CREATE TABLE IF NOT EXISTS OAUTH_ACCESS_TOKEN (
  TOKEN_ID VARCHAR(200),
  TOKEN BLOB,
  AUTHENTICATION_ID VARCHAR(200),
  USER_NAME VARCHAR(200),
  CLIENT_ID VARCHAR(200),
  AUTHENTICATION BLOB,
  REFRESH_TOKEN VARCHAR(200)
);

CREATE TABLE IF NOT EXISTS OAUTH_REFRESH_TOKEN (
  TOKEN_ID VARCHAR(200),
  TOKEN BLOB,
  AUTHENTICATION BLOB
);

CREATE TABLE IF NOT EXISTS OAUTH_CODE (
  CODE VARCHAR(200), AUTHENTICATION BLOB
);

CREATE TABLE IF NOT EXISTS USERS (
  ID INT AUTO_INCREMENT PRIMARY KEY,
  USERNAME VARCHAR(200) NOT NULL,
  PASSWORD VARCHAR(200) NOT NULL,
  ENABLED TINYINT(1),
  UNIQUE KEY UNIQUE_USERNAME(USERNAME)
);

CREATE TABLE IF NOT EXISTS AUTHORITIES (
  USERNAME VARCHAR(200) NOT NULL,
  AUTHORITY VARCHAR(200) NOT NULL,
  PRIMARY KEY(USERNAME, AUTHORITY)
);